services:
  - type: web
    name: al-in-finance
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000  # Render 会注入这个，默认不用写
